In [2]:
import dash
from dash import dcc, html, Input, Output
import dash_bootstrap_components as dbc
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import geopandas as gpd
from shapely import wkt

In [5]:
'/Users/user1/Documents/fertility_rates_app/smooth_asfr_lad_agg_cy.csv'
'/Users/user1/Documents/fertility_rates_app/smooth_tfr_lad_agg_cy.csv'
#read csv
asfr_df = pd.read_csv('/Users/user1/Documents/fertility_rates_app/smooth_asfr_lad_agg_cy.csv')
tfr_df = pd.read_csv('/Users/user1/Documents/fertility_rates_app/smooth_tfr_lad_agg_cy.csv')

In [6]:
#read GeoJSON
lad23_gdf = gpd.read_file('/Users/user1/Downloads/Local_Authority_Districts_May_2023_UK_BFE_V2_-3174526116983389398.geojson')

In [7]:
#simplify geometries
lad23_gdf['geometry'] = lad23_gdf['geometry'].simplify(tolerance=0.01)

In [8]:
tfr_df

        gss_code    gss_name  year geography       tfr
0      E06000001  Hartlepool  1993     LAD23  1.958386
1      E06000001  Hartlepool  1994     LAD23  1.964266
2      E06000001  Hartlepool  1995     LAD23  2.036165
3      E06000001  Hartlepool  1996     LAD23  1.876056
4      E06000001  Hartlepool  1997     LAD23  1.912876
...          ...         ...   ...       ...       ...
11341  W92000004       Wales  2019      CTRY  1.539042
11342  W92000004       Wales  2020      CTRY  1.478008
11343  W92000004       Wales  2021      CTRY  1.480045
11344  W92000004       Wales  2022      CTRY  1.444104
11345  W92000004       Wales  2023      CTRY  1.373506

[11346 rows x 5 columns]

In [9]:
asfr_df.head()

   age   gss_code     sex  year    gss_name geography  fertility_rate
0   15  E06000001  female  1993  Hartlepool     LAD23        0.054911
1   16  E06000001  female  1993  Hartlepool     LAD23        0.052579
2   17  E06000001  female  1993  Hartlepool     LAD23        0.052560
3   18  E06000001  female  1993  Hartlepool     LAD23        0.056454
4   19  E06000001  female  1993  Hartlepool     LAD23        0.065055

In [11]:
#merge geodata with asfr and tfr data on LAD23CD
asfr_merged = lad23_gdf.merge(asfr_df, left_on='LAD23CD', right_on='gss_code')
tfr_merged = lad23_gdf.merge(tfr_df, left_on='LAD23CD', right_on='gss_code')   
# Save as g
asfr_merged.to_file("asfr_merged.geojson", driver='GeoJSON')
tfr_merged.to_file("tfr_merged.geojson", driver='GeoJSON')

In [12]:
asfr_merged

,FID,LAD23CD,LAD23NM,LAD23NMW,BNG_E,BNG_N,LONG,LAT,GlobalID,geometry,age,gss_code,sex,year,gss_name,geography,fertility_rate
0,1,E06000001,Hartlepool,,447160,531474,-1.27018,54.67614,625a5484-2e3b-48e6-9432-f8fe739d51ae,"POLYGON ((-1.26846 54.72612, -1.17738 54.70118...",15,E06000001,female,1993,Hartlepool,LAD23,0.054911
1,1,E06000001,Hartlepool,,447160,531474,-1.27018,54.67614,625a5484-2e3b-48e6-9432-f8fe739d51ae,"POLYGON ((-1.26846 54.72612, -1.17738 54.70118...",16,E06000001,female,1993,Hartlepool,LAD23,0.052579
2,1,E06000001,Hartlepool,,447160,531474,-1.27018,54.67614,625a5484-2e3b-48e6-9432-f8fe739d51ae,"POLYGON ((-1.26846 54.72612, -1.17738 54.70118...",17,E06000001,female,1993,Hartlepool,LAD23,0.052560
3,1,E06000001,Hartlepool,,447160,531474,-1.27018,54.67614,625a5484-2e3b-48e6-9432-f8fe739d51ae,"POLYGON ((-1.26846 54.72612, -1.17738 54.70118...",18,E06000001,female,1993,Hartlepool,LAD23,0.056454
4,1,E06000001,Hartlepool,,447160,531474,-1.27018,54.67614,625a5484-2e3b-48e6-9432-f8fe739d51ae,"POLYGON ((-1.26846 54.72612, -1.17738 54.70118...",19,E06000001,female,1993,Hartlepool,LAD23,0.065055
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345025,361,W06000024,Merthyr Tydfil,Merthyr Tudful,305916,206424,-3.36425,51.74858,4ca54f0d-97ad-40f7-a74b-3069825271c1,"POLYGON ((-3.41713 51.8351, -3.35754 51.80698,...",45,W06000024,female,2023,Merthyr Tydfil,LAD23,0.004194
345026,361,W06000024,Merthyr Tydfil,Merthyr Tudful,305916,206424,-3.36425,51.74858,4ca54f0d-97ad-40f7-a74b-3069825271c1,"POLYGON ((-3.41713 51.8351, -3.35754 51.80698,...",46,W06000024,female,2023,Merthyr Tydfil,LAD23,0.003381
345027,361,W06000024,Merthyr Tydfil,Merthyr Tudful,305916,206424,-3.36425,51.74858,4ca54f0d-97ad-40f7-a74b-3069825271c1,"POLYGON ((-3.41713 51.8351, -3.35754 51.80698,...",47,W06000024,female,2023,Merthyr Tydfil,LAD23,0.002746
345028,361,W06000024,Merthyr Tydfil,Merthyr Tudful,305916,206424,-3.36425,51.74858,4ca54f0d-97ad-40f7-a74b-3069825271c1,"POLYGON ((-3.41713 51.8351, -3.35754 51.80698,...",48,W06000024,female,2023,Merthyr Tydfil,LAD23,0.002244
345029,361,W06000024,Merthyr Tydfil,Merthyr Tudful,305916,206424,-3.36425,51.74858,4ca54f0d-97ad-40f7-a74b-3069825271c1,"POLYGON ((-3.41713 51.8351, -3.35754 51.80698,...",49,W06000024,female,2023,Merthyr Tydfil,LAD23,0.001844

In [9]:
tfr_merged

,FID,LAD23CD,LAD23NM,LAD23NMW,BNG_E,BNG_N,LONG,LAT,GlobalID,geometry,gss_code,gss_name,year,geography,tfr
0,1,E06000001,Hartlepool,,447160,531474,-1.27018,54.67614,625a5484-2e3b-48e6-9432-f8fe739d51ae,"POLYGON ((-1.26846 54.72612, -1.17738 54.70118...",E06000001,Hartlepool,1993,LAD23,1.958386
1,1,E06000001,Hartlepool,,447160,531474,-1.27018,54.67614,625a5484-2e3b-48e6-9432-f8fe739d51ae,"POLYGON ((-1.26846 54.72612, -1.17738 54.70118...",E06000001,Hartlepool,1994,LAD23,1.964266
2,1,E06000001,Hartlepool,,447160,531474,-1.27018,54.67614,625a5484-2e3b-48e6-9432-f8fe739d51ae,"POLYGON ((-1.26846 54.72612, -1.17738 54.70118...",E06000001,Hartlepool,1995,LAD23,2.036165
3,1,E06000001,Hartlepool,,447160,531474,-1.27018,54.67614,625a5484-2e3b-48e6-9432-f8fe739d51ae,"POLYGON ((-1.26846 54.72612, -1.17738 54.70118...",E06000001,Hartlepool,1996,LAD23,1.876056
4,1,E06000001,Hartlepool,,447160,531474,-1.27018,54.67614,625a5484-2e3b-48e6-9432-f8fe739d51ae,"POLYGON ((-1.26846 54.72612, -1.17738 54.70118...",E06000001,Hartlepool,1997,LAD23,1.912876
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9853,361,W06000024,Merthyr Tydfil,Merthyr Tudful,305916,206424,-3.36425,51.74858,4ca54f0d-97ad-40f7-a74b-3069825271c1,"POLYGON ((-3.41713 51.8351, -3.35754 51.80698,...",W06000024,Merthyr Tydfil,2019,LAD23,1.569868
9854,361,W06000024,Merthyr Tydfil,Merthyr Tudful,305916,206424,-3.36425,51.74858,4ca54f0d-97ad-40f7-a74b-3069825271c1,"POLYGON ((-3.41713 51.8351, -3.35754 51.80698,...",W06000024,Merthyr Tydfil,2020,LAD23,1.583815
9855,361,W06000024,Merthyr Tydfil,Merthyr Tudful,305916,206424,-3.36425,51.74858,4ca54f0d-97ad-40f7-a74b-3069825271c1,"POLYGON ((-3.41713 51.8351, -3.35754 51.80698,...",W06000024,Merthyr Tydfil,2021,LAD23,1.592302
9856,361,W06000024,Merthyr Tydfil,Merthyr Tudful,305916,206424,-3.36425,51.74858,4ca54f0d-97ad-40f7-a74b-3069825271c1,"POLYGON ((-3.41713 51.8351, -3.35754 51.80698,...",W06000024,Merthyr Tydfil,2022,LAD23,1.611674
9857,361,W06000024,Merthyr Tydfil,Merthyr Tudful,305916,206424,-3.36425,51.74858,4ca54f0d-97ad-40f7-a74b-3069825271c1,"POLYGON ((-3.41713 51.8351, -3.35754 51.80698,...",W06000024,Merthyr Tydfil,2023,LAD23,1.527786

In [10]:
# Simple TFR map for 1993 only
def create_simple_tfr_map_1993():
    """Create a simple TFR map for the year 1993"""
    
    # Filter for 1993 data
    test_year = 1993
    tfr_1993 = tfr_merged[tfr_merged['year'] == test_year].copy()
    
    print(f"TFR data for {test_year}:")
    print(f"Data shape: {tfr_1993.shape}")
    print(f"Number of locations: {len(tfr_1993)}")
    print(f"TFR range: {tfr_1993['tfr'].min():.3f} to {tfr_1993['tfr'].max():.3f}")
    print(f"Average TFR: {tfr_1993['tfr'].mean():.3f}")
    
    if tfr_1993.empty:
        print(f"No data available for year {test_year}")
        return None
    
    # Convert to web mercator if needed
    tfr_gdf_web = tfr_1993.to_crs('EPSG:4326') if tfr_1993.crs != 'EPSG:4326' else tfr_1993
    
    # Create the map
    fig = go.Figure()
    
    # Get TFR range for colour scaling
    tfr_min = tfr_1993['tfr'].min()
    tfr_max = tfr_1993['tfr'].max()
    
    # Create the choropleth trace
    fig.add_trace(
        go.Choroplethmapbox(
            geojson=tfr_gdf_web.__geo_interface__,
            locations=tfr_gdf_web.index,
            z=tfr_gdf_web['tfr'],
            colorscale='RdYlBu_r',  # Red-Yellow-Blue reversed (red = high fertility)
            zmin=tfr_min,
            zmax=tfr_max,
            text=tfr_gdf_web['gss_name'],
            hovertemplate='<b>%{text}</b><br>' + 
                         f'TFR ({test_year}): %{{z:.3f}}<br>' +
                         'UK Replacement Level: 2.1<extra></extra>',
            marker_opacity=0.8,
            marker_line_width=0.5,
            marker_line_color='white',
            colorbar=dict(
                title=f"Total Fertility Rate ({test_year})", 
                title_side="right",
                len=0.8,
                thickness=15
            )
        )
    )
    
    # Update layout
    fig.update_layout(
        title=dict(
            text=f'Total Fertility Rate Across UK Local Authority Districts ({test_year})',
            x=0.5,
            font=dict(size=16, color='#2E8B57')
        ),
        mapbox=dict(
            style='carto-positron',
            center={'lat': 54.5, 'lon': -2.5},
            zoom=5.2
        ),
        height=700,
        width=1100,
        font=dict(family="Arial", size=12)
    )
    
    return fig

# Create and display the simple TFR map for 1993
print("Creating simple TFR map for 1993...")
fig_tfr_1993 = create_simple_tfr_map_1993()

if fig_tfr_1993:
    fig_tfr_1993.show()
    print("✅ TFR map for 1993 created successfully!")
    print("🎯 Red areas = higher fertility rates, Blue areas = lower fertility rates")
else:
    print("❌ Failed to create TFR map for 1993")

Creating simple TFR map for 1993...
TFR data for 1993:
Data shape: (318, 15)
Number of locations: 318
TFR range: 0.996 to 2.313
Average TFR: 1.778

/var/folders/k7/sydv9mbx0kz7fx7373rx_2100000gp/T/ipykernel_1129/2081314499.py:31: DeprecationWarning:

*choroplethmapbox* is deprecated! Use *choroplethmap* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/

✅ TFR map for 1993 created successfully!
🎯 Red areas = higher fertility rates, Blue areas = lower fertility rates

In [ ]:
import dash
from dash import dcc, html, Input, Output
import plotly.express as px
import geopandas as gpd

# --- Load and prepare your GeoDataFrame ---
# Make sure tfr_merged is loaded as a GeoDataFrame
# Columns needed: ['LAD23CD', 'LAD23NM', 'geometry', 'year', 'tfr']

# Ensure CRS is WGS84 for Mapbox
if tfr_merged.crs is None:
    tfr_merged = tfr_merged.set_crs("EPSG:27700", allow_override=True)
tfr_merged = tfr_merged.to_crs(epsg=4326)

# Simplify geometry for faster rendering
tfr_merged['geometry'] = tfr_merged['geometry'].simplify(tolerance=0.005, preserve_topology=True)
tfr_merged = tfr_merged[tfr_merged.is_valid].reset_index(drop=True)

# Create GeoJSON
tfr_geojson = tfr_merged.__geo_interface__

# Get list of years
years = sorted(tfr_merged['year'].unique())

# --- Initialize Dash app ---
app = dash.Dash(__name__)
app.title = "UK Total Fertility Rate (TFR) by Year"

# --- App Layout ---
app.layout = html.Div([
    html.H2(" UK Total Fertility Rate (TFR) by Local Authority", 
            style={'textAlign': 'center'}),

    html.Div([
        html.Label("Select Year:"),
        dcc.Slider(
            id='year-slider',
            min=years[0],
            max=years[-1],
            step=1,
            marks={str(year): str(year) for year in years},  # keys must be strings
            value=years[0],
            tooltip={"placement": "bottom", "always_visible": True}
        )
    ], style={'width': '80%', 'margin': '0 auto', 'marginBottom': '20px'}),

    dcc.Graph(id='tfr-map', style={'height': '80vh'})
])

# --- Callback to update map ---
@app.callback(
    Output('tfr-map', 'figure'),
    Input('year-slider', 'value')
)
def update_map(selected_year):
    filtered = tfr_merged[tfr_merged['year'] == selected_year]

    # Create choropleth
    fig = px.choropleth_mapbox(
        filtered,
        geojson=tfr_geojson,
        locations='LAD23CD',
        featureidkey='properties.LAD23CD',
        color='tfr',
        hover_name='LAD23NM',
        hover_data={'tfr': True, 'year': True, 'LAD23CD': False},
        color_continuous_scale='Viridis',
        mapbox_style='carto-positron',
        zoom=5,
        center={"lat": 54.5, "lon": -2.5},
        opacity=0.7,
        title=f"UK Total Fertility Rate ({selected_year})"
    )

    fig.update_layout(margin={"r":0,"t":40,"l":0,"b":0})
    return fig

# --- Run app ---
if __name__ == '__main__':
    app.run(debug=True, port=8051)

/var/folders/k7/sydv9mbx0kz7fx7373rx_2100000gp/T/ipykernel_1129/2122723088.py:59: DeprecationWarning:

*choropleth_mapbox* is deprecated! Use *choropleth_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/

In [12]:
# --- Prepare GeoDataFrame ---
# Keep only necessary columns
tfr_merged = tfr_merged[['LAD23CD', 'LAD23NM', 'geometry', 'year', 'tfr']].copy()

# Ensure CRS is WGS84 for Mapbox
if tfr_merged.crs is None:
    tfr_merged = tfr_merged.set_crs("EPSG:27700", allow_override=True)
tfr_merged = tfr_merged.to_crs(epsg=4326)

# Simplify geometry for faster rendering
tfr_merged['geometry'] = tfr_merged['geometry'].simplify(tolerance=0.01, preserve_topology=True)
tfr_merged = tfr_merged[tfr_merged.is_valid].reset_index(drop=True)

# Get list of years
years = sorted(tfr_merged['year'].unique())

# --- Initialize Dash app ---
app = dash.Dash(__name__)
app.title = "UK Total Fertility Rate (TFR) by Year"

# --- Layout ---
app.layout = html.Div([
    html.H2(" UK Total Fertility Rate (TFR) by Local Authority", 
            style={'textAlign': 'center'}),

    html.Div([
        html.Label("Select Year:"),
        dcc.Slider(
            id='year-slider',
            min=years[0],
            max=years[-1],
            step=1,
            marks={str(year): str(year) for year in years},
            value=years[0],
            tooltip={"placement": "bottom", "always_visible": True}
        )
    ], style={'width': '80%', 'margin': '0 auto', 'marginBottom': '20px'}),

    dcc.Graph(id='tfr-map', style={'height': '80vh'})
])

# --- Callback ---
@app.callback(
    Output('tfr-map', 'figure'),
    Input('year-slider', 'value')
)
def update_map(selected_year):
    # Filter only the selected year
    filtered = tfr_merged[tfr_merged['year'] == selected_year]

    # Generate GeoJSON for filtered data only (much faster)
    filtered_geojson = filtered.__geo_interface__

    fig = px.choropleth_mapbox(
        filtered,
        geojson=filtered_geojson,
        locations='LAD23CD',
        featureidkey='properties.LAD23CD',
        color='tfr',
        hover_name='LAD23NM',
        hover_data={'tfr': True, 'year': True, 'LAD23CD': False},
        color_continuous_scale='Viridis',
        mapbox_style='carto-positron',
        zoom=5,
        center={"lat": 54.5, "lon": -2.5},
        opacity=0.7,
        title=f"UK Total Fertility Rate ({selected_year})"
    )

    fig.update_layout(margin={"r":0,"t":40,"l":0,"b":0})
    return fig

# --- Run app ---
if __name__ == '__main__':
    app.run(debug=True, port=8051)

In [13]:
# Keep only necessary columns for speed
asfr_merged = asfr_merged[['LAD23CD','LAD23NM','geometry','age','year','fertility_rate']].copy()

# Ensure CRS is WGS84 for Mapbox
if asfr_merged.crs is None:
    asfr_merged = asfr_merged.set_crs("EPSG:27700", allow_override=True)
asfr_merged = asfr_merged.to_crs(epsg=4326)

# Simplify geometry for faster rendering
asfr_merged['geometry'] = asfr_merged['geometry'].simplify(tolerance=0.01, preserve_topology=True)
asfr_merged = asfr_merged[asfr_merged.is_valid].reset_index(drop=True)

# Get list of years and ages
years = sorted(asfr_merged['year'].unique())
ages = sorted(asfr_merged['age'].unique())

# --- Initialize Dash app ---
app = dash.Dash(__name__)
app.title = "UK Age-Specific Fertility Rate (ASFR)"

# --- App Layout ---
app.layout = html.Div([
    html.H2(" UK Age-Specific Fertility Rate (ASFR) by Local Authority", 
            style={'textAlign': 'center'}),

    # Year slider
    html.Div([
        html.Label("Select Year:"),
        dcc.Slider(
            id='year-slider',
            min=years[0],
            max=years[-1],
            step=1,
            marks={str(year): str(year) for year in years},
            value=years[0],
            tooltip={"placement": "bottom", "always_visible": True}
        )
    ], style={'width': '80%', 'margin': '0 auto', 'marginBottom': '20px'}),

    # Age dropdown
    html.Div([
        html.Label("Select Age:"),
        dcc.Dropdown(
            id='age-dropdown',
            options=[{'label': str(a), 'value': a} for a in ages],
            value=ages[0],
            clearable=False,
            style={'width': '200px', 'margin': '0 auto'}
        )
    ], style={'textAlign': 'center', 'marginBottom': '20px'}),

    # Map
    dcc.Graph(id='asfr-map', style={'height': '80vh'})
])

# --- Callback to update map ---
@app.callback(
    Output('asfr-map', 'figure'),
    Input('year-slider', 'value'),
    Input('age-dropdown', 'value')
)
def update_map(selected_year, selected_age):
    # Filter data for selected year and age
    filtered = asfr_merged[
        (asfr_merged['year'] == selected_year) &
        (asfr_merged['age'] == selected_age)
    ]

    # Generate GeoJSON only for filtered rows (much faster)
    filtered_geojson = filtered.__geo_interface__

    # Create choropleth map
    fig = px.choropleth_mapbox(
        filtered,
        geojson=filtered_geojson,
        locations='LAD23CD',
        featureidkey='properties.LAD23CD',
        color='fertility_rate',
        hover_name='LAD23NM',
        hover_data={'fertility_rate': True, 'year': True, 'age': True, 'LAD23CD': False},
        color_continuous_scale='Viridis',
        mapbox_style='carto-positron',
        zoom=5,
        center={"lat": 54.5, "lon": -2.5},
        opacity=0.7,
        title=f"UK ASFR ({selected_year}, Age {selected_age})"
    )

    fig.update_layout(margin={"r":0,"t":40,"l":0,"b":0})
    return fig

# --- Run app ---
if __name__ == '__main__':
    app.run(debug=True, port=8053)

In [13]:
import dash
from dash import dcc, html, Input, Output
import plotly.express as px

# --- Use actual data ---
# tfr_merged: ['LAD23CD','LAD23NM','year','tfr']
# asfr_merged: ['LAD23CD','LAD23NM','year','age','fertility_rate']

lads = sorted(tfr_merged['LAD23NM'].unique())
ages = sorted(asfr_merged['age'].unique())

# --- Initialize Dash app ---
app = dash.Dash(__name__)
app.title = "TFR & ASFR Line Graphs by LAD"

# --- Layout ---
app.layout = html.Div([
    html.H2("👶 Fertility Trends by Local Authority", style={'textAlign': 'center'}),

    html.Div([
        # TFR controls
        html.Div([
            html.Label("Select LAD (TFR):"),
            dcc.Dropdown(
                id='tfr-lad-dropdown',
                options=[{'label': lad, 'value': lad} for lad in lads],
                value=lads[0],
                clearable=False,
                style={'width': '200px'}
            ),
            dcc.Graph(id='tfr-line')
        ], style={'flex': 1, 'marginRight': '20px'}),

        # ASFR controls
        html.Div([
            html.Label("Select LAD (ASFR):"),
            dcc.Dropdown(
                id='asfr-lad-dropdown',
                options=[{'label': lad, 'value': lad} for lad in lads],
                value=lads[0],
                clearable=False,
                style={'width': '200px', 'marginBottom': '10px'}
            ),
            html.Label("Select Age:"),
            dcc.Dropdown(
                id='asfr-age-dropdown',
                options=[{'label': str(a), 'value': a} for a in ages],
                value=ages[0],
                clearable=False,
                style={'width': '100px', 'marginBottom': '10px'}
            ),
            dcc.Graph(id='asfr-line')
        ], style={'flex': 1})
    ], style={'display': 'flex', 'justifyContent': 'space-around', 'alignItems': 'flex-start'})
])

# --- Callbacks ---
@app.callback(
    Output('tfr-line', 'figure'),
    Input('tfr-lad-dropdown', 'value')
)
def update_tfr_line(selected_lad):
    filtered = tfr_merged[tfr_merged['LAD23NM'] == selected_lad]
    fig = px.line(
        filtered,
        x='year',
        y='tfr',
        title=f"TFR Over Time - {selected_lad}",
        markers=True
    )
    return fig

@app.callback(
    Output('asfr-line', 'figure'),
    Input('asfr-lad-dropdown', 'value'),
    Input('asfr-age-dropdown', 'value')
)
def update_asfr_line(selected_lad, selected_age):
    filtered = asfr_merged[
        (asfr_merged['LAD23NM'] == selected_lad) &
        (asfr_merged['age'] == selected_age)
    ]
    fig = px.line(
        filtered,
        x='year',
        y='fertility_rate',
        title=f"ASFR Over Time - {selected_lad} (Age {selected_age})",
        markers=True
    )
    return fig

# --- Run app ---
if __name__ == '__main__':
    app.run(debug=True, port=8057)

In [16]:
# FERTILITY DASHBOARD

import dash
import dash_bootstrap_components as dbc
from dash import dcc, html, Input, Output, State
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd
import json


# Clean TFR data
tfr_clean = tfr_merged[['LAD23CD', 'LAD23NM', 'geometry', 'year', 'tfr']].copy()
if tfr_clean.crs is None:
    tfr_clean = tfr_clean.set_crs("EPSG:27700", allow_override=True)
tfr_clean = tfr_clean.to_crs(epsg=4326)
tfr_clean['geometry'] = tfr_clean['geometry'].simplify(tolerance=0.007, preserve_topology=True)
tfr_clean = tfr_clean[tfr_clean.is_valid].reset_index(drop=True)

# Clean ASFR data  
asfr_clean = asfr_merged[['LAD23CD','LAD23NM','geometry','age','year','fertility_rate']].copy()
if asfr_clean.crs is None:
    asfr_clean = asfr_clean.set_crs("EPSG:27700", allow_override=True)
asfr_clean = asfr_clean.to_crs(epsg=4326)
asfr_clean['geometry'] = asfr_clean['geometry'].simplify(tolerance=0.007, preserve_topology=True)
asfr_clean = asfr_clean[asfr_clean.is_valid].reset_index(drop=True)

# Convert to strings for serialisation
years = sorted([str(year) for year in tfr_clean['year'].unique()])
ages = sorted([str(age) for age in asfr_clean['age'].unique()])
lads = sorted(tfr_clean['LAD23NM'].unique())

# Ensure string columns
tfr_clean['year'] = tfr_clean['year'].astype(str)
asfr_clean['year'] = asfr_clean['year'].astype(str) 
asfr_clean['age'] = asfr_clean['age'].astype(str)

print(f"Enhanced dashboard ready: {len(years)} years, {len(ages)} ages, {len(lads)} LADs")

# Initialise Dash App
app = dash.Dash(__name__, external_stylesheets=[dbc.themes.SANDSTONE])
app.title = "UK Fertility Dashboard - Enhanced"

# loading spinner
app.index_string = '''
<!DOCTYPE html>
<html>
    <head>
        {%metas%}
        <title>{%title%}</title>
        <link rel="icon" href="https://resource.esriuk.com/wp-content/uploads/2017/06/GLA-Logo-Resized.png" type="image/png">
        {%favicon%}
        {%css%}
        <style>
            /* Professional Loading Spinner Overlay */
            .loading-overlay {
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                background: linear-gradient(135deg, #1e3a8a 0%, #ea580c 100%);
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
                z-index: 9999;
                transition: opacity 0.5s ease-out;
            }
            
            /* Enhanced Spinner Animation */
            .spinner {
                width: 80px;
                height: 80px;
                border: 6px solid rgba(255, 255, 255, 0.3);
                border-top: 6px solid white;
                border-radius: 50%;
                animation: spin 1s linear infinite;
                margin-bottom: 20px;
            }
            
            @keyframes spin {
                0% { transform: rotate(0deg); }
                100% { transform: rotate(360deg); }
            }
            
            /* Professional Loading Text */
            .loading-text {
                color: white;
                font-family: "Arial", sans-serif;
                font-size: 28px;
                font-weight: bold;
                text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
                margin-bottom: 10px;
                letter-spacing: 1px;
            }
            
            .loading-subtext {
                color: rgba(255, 255, 255, 0.95);
                font-family: "Arial", sans-serif;
                font-size: 16px;
                text-align: center;
                max-width: 350px;
                font-weight: 300;
            }
            
            /* GLA logo in loading screen */
            .loading-logo {
                width: 70px;
                height: 70px;
                margin-bottom: 30px;
                border-radius: 50%;
                background: white;
                display: flex;
                align-items: center;
                justify-content: center;
                box-shadow: 0 6px 20px rgba(0,0,0,0.25);
                animation: pulse 2s infinite;
            }
            
            @keyframes pulse {
                0% { transform: scale(1); }
                50% { transform: scale(1.05); }
                100% { transform: scale(1); }
            }
            
            .loading-logo img {
                width: 50px;
                height: 50px;
                object-fit: contain;
            }
            
            /* Enhanced Card Styling */
            .metric-card {
                transition: transform 0.2s ease-in-out, box-shadow 0.2s ease-in-out;
                border-radius: 12px !important;
            }
            
            .metric-card:hover {
                transform: translateY(-2px);
                box-shadow: 0 8px 25px rgba(0,0,0,0.15) !important;
            }
            
            /* Professional Control Panel */
            .control-panel {
                background: linear-gradient(145deg, #ffffff 0%, #f8f9fa 100%);
                border-radius: 15px;
                box-shadow: 0 4px 15px rgba(0,0,0,0.1);
            }
            
            /* Enhanced Graph Containers */
            .graph-container {
                border-radius: 15px;
                overflow: hidden;
                box-shadow: 0 6px 20px rgba(0,0,0,0.12);
                transition: box-shadow 0.3s ease;
            }
            
            .graph-container:hover {
                box-shadow: 0 8px 25px rgba(0,0,0,0.18);
            }
            
            /* Professional Typography */
            .dashboard-title {
                background: linear-gradient(45deg, #1e3a8a, #ea580c);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                background-clip: text;
                font-weight: 800;
                letter-spacing: -0.5px;
            }
            
            /* Custom Dropdown Styling */
            .Select-control {
                border-radius: 8px !important;
                border: 2px solid #e9ecef !important;
                transition: all 0.2s ease !important;
            }
            
            .Select-control:hover {
                border-color: #1e3a8a !important;
            }
        </style>
    </head>
    <body>
        <!-- Enhanced Loading Overlay -->
        <div id="loading-overlay" class="loading-overlay">
            <div class="loading-logo">
                <img src="https://resource.esriuk.com/wp-content/uploads/2017/06/GLA-Logo-Resized.png" alt="GLA Logo">
            </div>
            <div class="spinner"></div>
            <div class="loading-text">UK Fertility Dashboard</div>
            <div class="loading-subtext">Loading comprehensive fertility rate analysis and interactive visualisations...</div>
        </div>
        
        {%app_entry%}
        <footer>
            {%config%}
            {%scripts%}
            {%renderer%}
        </footer>
        
        <script>
            // Enhanced loading overlay management
            window.addEventListener('load', function() {
                setTimeout(function() {
                    const overlay = document.getElementById('loading-overlay');
                    if (overlay) {
                        overlay.style.opacity = '0';
                        setTimeout(function() {
                            overlay.style.display = 'none';
                        }, 500);
                    }
                }, 1200); // Extended display for professional feel
            });
            
            // Dash readiness detection
            document.addEventListener('DOMContentLoaded', function() {
                const checkDashReady = setInterval(function() {
                    const dashContainer = document.querySelector('[data-dash-is-loading="false"]');
                    if (dashContainer) {
                        clearInterval(checkDashReady);
                        setTimeout(function() {
                            const overlay = document.getElementById('loading-overlay');
                            if (overlay && overlay.style.display !== 'none') {
                                overlay.style.opacity = '0';
                                setTimeout(function() {
                                    overlay.style.display = 'none';
                                }, 500);
                            }
                        }, 600);
                    }
                }, 100);
            });
        </script>
    </body>
</html>
'''

#colour scheme -  Orange & Blue
colors = {
    'primary': '#1e3a8a',      # Deep blue
    'secondary': '#ea580c',    # Stylish orange  
    'accent': '#3b82f6',       # Bright blue accent
    'background': '#F8F9FA',   # Light background
    'text': '#2C3E50',         # Dark text
    'success': '#1d4ed8',      # Success blue
    'warning': '#f59e0b',      # Warning orange
    'card_bg': '#ffffff'       # Pure white cards
}

#Layout
app.layout = dbc.Container([
    
    # Professional Header
    dbc.Row([
        dbc.Col([
            html.Div([
                html.H1("UK Fertility Rate Dashboard", 
                       className="text-center mb-3 dashboard-title",
                       style={'fontSize': '3rem', 'fontWeight': '800', 'marginTop': '20px'}),
                html.H4("Comprehensive Analysis of Total & Age-Specific Fertility Rates (1993-2023)",
                       className="text-center text-muted mb-4",
                       style={'fontWeight': '300', 'letterSpacing': '0.5px'}),
                html.Hr(style={'borderColor': colors['secondary'], 'borderWidth': '3px', 
                              'width': '60%', 'margin': '0 auto', 'marginBottom': '30px'})
            ])
        ])
    ]),
    
    # Control Panel
    dbc.Card([
        dbc.CardBody([
            html.H4("Dashboard Controls", className="mb-4", 
                   style={'color': colors['primary'], 'fontWeight': '600'}),
            
            dbc.Row([
                # Year Dropdown with enhanced styling
                dbc.Col([
                    html.Label("Select Year", className="fw-bold mb-2",
                              style={'color': colors['text'], 'fontSize': '14px'}),
                    dcc.Dropdown(
                        id='year-dropdown',
                        options=[{'label': year, 'value': year} for year in years],
                        value=years[-1],
                        clearable=False,
                        style={'marginBottom': '15px'}
                    )
                ], width=4),
                
                # Age Dropdown with enhanced styling
                dbc.Col([
                    html.Label("Select Age (ASFR)", className="fw-bold mb-2",
                              style={'color': colors['text'], 'fontSize': '14px'}),
                    dcc.Dropdown(
                        id='age-dropdown',
                        options=[{'label': f"Age {age}", 'value': age} for age in ages],
                        value="30",
                        clearable=False,
                        style={'marginBottom': '15px'}
                    )
                ], width=4),
                
                # LAD Dropdown with search
                dbc.Col([
                    html.Label("Local Authority", className="fw-bold mb-2",
                              style={'color': colors['text'], 'fontSize': '14px'}),
                    dcc.Dropdown(
                        id='lad-dropdown',
                        options=[{'label': lad, 'value': lad} for lad in lads[:100]],
                        value="Manchester",
                        clearable=False,
                        placeholder="Search Local Authority...",
                        style={'marginBottom': '15px'}
                    )
                ], width=4)
            ])
        ])
    ], className="mb-4 control-panel"),
    
    # Summary Metrics
    dbc.Row([
        dbc.Col([
            dbc.Card([
                dbc.CardBody([
                    html.Div([
                        html.H4(id="tfr-title", children="Total Fertility Rate", style={'color': colors['primary'], 'fontWeight': '600'}),
                        html.H2(id="current-tfr", children="--", 
                               style={'color': colors['secondary'], 'fontWeight': '700', 'fontSize': '2.5rem'})
                    ], className="text-center")
                ])
            ], className="metric-card", style={'backgroundColor': colors['card_bg'], 
                                              'borderLeft': f'5px solid {colors["secondary"]}',
                                              'boxShadow': '0 4px 15px rgba(0,0,0,0.1)'})
        ], width=4),
        
        dbc.Col([
            dbc.Card([
                dbc.CardBody([
                    html.Div([
                        html.H4(id="comparison-title", children="vs UK Average", style={'color': colors['primary'], 'fontWeight': '600'}),
                        html.H2(id="tfr-comparison", children="--", 
                               style={'color': colors['accent'], 'fontWeight': '700', 'fontSize': '2.5rem'})
                    ], className="text-center")
                ])
            ], className="metric-card", style={'backgroundColor': colors['card_bg'], 
                                              'borderLeft': f'5px solid {colors["accent"]}',
                                              'boxShadow': '0 4px 15px rgba(0,0,0,0.1)'})
        ], width=4),
        
        dbc.Col([
            dbc.Card([
                dbc.CardBody([
                    html.Div([
                        html.H4("Replacement Level", style={'color': colors['primary'], 'fontWeight': '600'}),
                        html.H2("2.1", style={'color': colors['warning'], 'fontWeight': '700', 'fontSize': '2.5rem'}),
                        html.P(id="replacement-status", children="--", className="text-muted")
                    ], className="text-center")
                ])
            ], className="metric-card", style={'backgroundColor': colors['card_bg'], 
                                              'borderLeft': f'5px solid {colors["warning"]}',
                                              'boxShadow': '0 4px 15px rgba(0,0,0,0.1)'})
        ], width=4)
    ], className="mb-4"),
    
    # Enhanced Maps Section
    dbc.Row([
        # TFR Map
        dbc.Col([
            dbc.Card([
                dbc.CardHeader([
                    html.H5("Total Fertility Rate Map", className="text-center mb-0",
                           style={'color': colors['primary'], 'fontWeight': '600'})
                ], style={'backgroundColor': colors['background']}),
                dbc.CardBody([
                    dcc.Graph(id='tfr-map', style={'height': '520px'})
                ], style={'padding': '0'})
            ], className="graph-container")
        ], width=6),
        
        # ASFR Map 
        dbc.Col([
            dbc.Card([
                dbc.CardHeader([
                    html.H5("Age-Specific Fertility Rate Map", className="text-center mb-0",
                           style={'color': colors['primary'], 'fontWeight': '600'})
                ], style={'backgroundColor': colors['background']}),
                dbc.CardBody([
                    dcc.Graph(id='asfr-map', style={'height': '520px'})
                ], style={'padding': '0'})
            ], className="graph-container")
        ], width=6)
    ], className="mb-4"),
    
    # Enhanced Trend Analysis
    dbc.Row([
        # TFR Trend 
        dbc.Col([
            dbc.Card([
                dbc.CardHeader([
                    html.H5("TFR Trend Analysis", className="text-center mb-0",
                           style={'color': colors['primary'], 'fontWeight': '600'})
                ], style={'backgroundColor': colors['background']}),
                dbc.CardBody([
                    dcc.Graph(id='tfr-trend', style={'height': '420px'})
                ], style={'padding': '0'})
            ], className="graph-container")
        ], width=6),
        
        # ASFR Trend 
        dbc.Col([
            dbc.Card([
                dbc.CardHeader([
                    html.H5("ASFR Trend Analysis", className="text-center mb-0",
                           style={'color': colors['primary'], 'fontWeight': '600'})
                ], style={'backgroundColor': colors['background']}),
                dbc.CardBody([
                    dcc.Graph(id='asfr-trend', style={'height': '420px'})
                ], style={'padding': '0'})
            ], className="graph-container")
        ], width=6)
    ], className="mb-4"),
    
    # Footer
    dbc.Row([
        dbc.Col([
            html.Hr(style={'borderColor': colors['secondary'], 'marginTop': '40px'}),
            dbc.Alert([
                html.H5("About This Dashboard", className="alert-heading",
                       style={'color': colors['primary'], 'fontWeight': 'bold'}),
                html.P([
                         "This dashboard provides analysis of UK fertility rates using the GLA Fertility Estimates. ",
                            "The code used to produce these estimates is available on ",
                            html.A(
                            "GitHub",  # Text that will show as a link
                        href="https://github.com/Greater-London-Authority/fertility_rate_estimation/tree/main",
                        target="_blank"  # Opens link in a new tab
                                   ,style={'color': colors['primary']}),
                        html.Br(),
                    html.Strong("TFR (Total Fertility Rate)"), " Total fertility rate (TFR) is a commonly used measure of overall fertility calculated as the sum of all age-specific fertility rates across all reproductive age groups. It represents the average number of children that a woman would have if she were to experience current age-specific fertility rates over the course of her life. For 2023, we estimate the TFR in Inner London to have been 1.16 compared to 1.54 in Outer London, and 1.41 for England as whole.",
                        html.Br(),
                    html.Strong("ASFR (Age-Specific Fertility Rate, 15 to 49)"), " Age-specific fertility rates (ASFR) measure the number of births per woman within specific age groups. For example, in England, the peak childbearing age is currently 32, with an ASFR of 0.107, meaning 107 babies were born for each 1,000 women aged 32.",
                    "The UK replacement fertility rate is approximately ", html.Strong("2.1 children per woman"), "."
                ], className="mb-2", style={'color': colors['primary']}),
                html.P([
                    "Use the controls above to explore different years, ages, and local authorities. ",
                    "Interactive maps maintain their fertility-specific colour schemes. ",
                    "Compare trends across time and regions with visualisations. Visualisations can be easily downloaded using the camera icon in the top-right corner of each graph."
                ], className="mb-0", style={'color': colors['primary']})
            ], color="navy", style={'backgroundColor': 'rgba(46, 139, 87, 0.1)', 
                                   'borderColor': colors['primary']}, className="mb-3"),
            
            html.P([
                "GLA Fertility Dashboard | Data: ONS | ",
                html.A("Office for National Statistics", 
                      href="https://www.ons.gov.uk", 
                      style={'color': colors['primary'], 'textDecoration': 'none'})
            ], className="text-center text-muted", style={'fontSize': '14px'})
        ])
    ])
    
], fluid=True, style={'padding': '25px', 'backgroundColor': colors['background'], 
                     'minHeight': '100vh'})

# ========== ENHANCED CALLBACKS (Same Logic, Professional Styling) ==========

# Update metrics with enhanced formatting
@app.callback(
    [Output('current-tfr', 'children'),
     Output('tfr-comparison', 'children'),
     Output('replacement-status', 'children')],
    [Input('year-dropdown', 'value'),
     Input('lad-dropdown', 'value')]
)
def update_metrics(selected_year, selected_lad):
    try:
        if selected_lad and selected_year:
            lad_tfr = tfr_clean[
                (tfr_clean['year'] == selected_year) & 
                (tfr_clean['LAD23NM'] == selected_lad)
            ]['tfr']
            
            if not lad_tfr.empty:
                current_tfr = lad_tfr.iloc[0]
                tfr_display = f"{current_tfr:.2f}"
                
                # Enhanced comparison formatting
                uk_avg = tfr_clean[tfr_clean['year'] == selected_year]['tfr'].mean()
                diff = current_tfr - uk_avg
                comparison = f"{diff:+.2f}"
                
                # Enhanced status indicators
                if current_tfr >= 2.1:
                    status = "Above replacement level"
                elif current_tfr >= 1.8:
                    status = f"Below by {2.1 - current_tfr:.2f}"
                else:
                    status = f"Below by {2.1 - current_tfr:.2f}"
                    
                return tfr_display, comparison, status
        
        return "Select Data", "N/A", "Choose LAD & Year"
        
    except Exception as e:
        print(f"Enhanced metrics error: {e}")
        return "Error", "Error", "Data Error"

# Enhanced TFR map (keeping RdYlBu_r colour scheme)
@app.callback(
    Output('tfr-map', 'figure'),
    [Input('year-dropdown', 'value')]
)
def update_tfr_map(selected_year):
    try:
        if not selected_year:
            return go.Figure().add_annotation(text="Please select a year", showarrow=False, 
                                           font=dict(size=16, color=colors['text']))
        
        filtered_tfr = tfr_clean[tfr_clean['year'] == selected_year]
        
        if filtered_tfr.empty:
            return go.Figure().add_annotation(text="No data available for selected year", 
                                           showarrow=False, font=dict(size=16, color=colors['text']))
        
        # Enhanced TFR map (KEEPING original fertility colour scheme)
        fig = px.choropleth_mapbox(
            filtered_tfr,
            geojson=filtered_tfr.__geo_interface__,
            locations='LAD23CD',
            featureidkey='properties.LAD23CD',
            color='tfr',
            hover_name='LAD23NM',
            hover_data={'tfr': ':.3f', 'LAD23CD': False},
            color_continuous_scale='RdYlBu_r',  # KEPT: Red=high, Blue=low fertility
            mapbox_style='carto-positron',
            zoom=5.3,
            center={"lat": 54.5, "lon": -2.5},
            opacity=0.85
        )
        
        fig.update_layout(
            title=dict(
                text=f"Total Fertility Rate ({selected_year})",
                x=0.5,
                font=dict(size=18, color=colors['primary'], family="Arial Black")
            ),
            margin={"r":5,"t":60,"l":5,"b":5},
            coloraxis_colorbar=dict(
                title="TFR",
                title_font=dict(size=14, color=colors['primary']),
                len=0.8,
                thickness=20
            )
        )
        
        return fig
        
    except Exception as e:
        print(f"Enhanced TFR map error: {e}")
        return go.Figure().add_annotation(text=f"Map Error: {str(e)[:50]}...", 
                                       showarrow=False, font=dict(size=14, color='red'))

# Enhanced ASFR map (keeping Plasma colour scheme)
@app.callback(
    Output('asfr-map', 'figure'),
    [Input('year-dropdown', 'value'),
     Input('age-dropdown', 'value')]
)
def update_asfr_map(selected_year, selected_age):
    try:
        if not selected_year or not selected_age:
            return go.Figure().add_annotation(text="Please select year and age", 
                                           showarrow=False, font=dict(size=16, color=colors['text']))
        
        filtered_asfr = asfr_clean[
            (asfr_clean['year'] == selected_year) &
            (asfr_clean['age'] == selected_age)
        ]
        
        if filtered_asfr.empty:
            return go.Figure().add_annotation(text="No data available for selection", 
                                           showarrow=False, font=dict(size=16, color=colors['text']))
        
        # Enhanced ASFR map (KEEPING original fertility colour scheme)
        fig = px.choropleth_mapbox(
            filtered_asfr,
            geojson=filtered_asfr.__geo_interface__,
            locations='LAD23CD',
            featureidkey='properties.LAD23CD',
            color='fertility_rate',
            hover_name='LAD23NM',
            hover_data={'fertility_rate': ':.4f', 'LAD23CD': False},
            color_continuous_scale='Plasma',  # KEPT: Original ASFR colour scheme
            mapbox_style='carto-positron',
            zoom=5.3,
            center={"lat": 54.5, "lon": -2.5},
            opacity=0.85
        )
        
        fig.update_layout(
            title=dict(
                text=f"ASFR Age {selected_age} ({selected_year})",
                x=0.5,
                font=dict(size=18, color=colors['primary'], family="Arial Black")
            ),
            margin={"r":5,"t":60,"l":5,"b":5},
            coloraxis_colorbar=dict(
                title=f"ASFR (Age {selected_age})",
                title_font=dict(size=14, color=colors['primary']),
                len=0.8,
                thickness=20
            )
        )
        
        return fig
        
    except Exception as e:
        print(f"Enhanced ASFR map error: {e}")
        return go.Figure().add_annotation(text=f"Map Error: {str(e)[:50]}...", 
                                       showarrow=False, font=dict(size=14, color='red'))

# Enhanced TFR trend with professional styling
@app.callback(
    Output('tfr-trend', 'figure'),
    [Input('lad-dropdown', 'value')]
)
def update_tfr_trend(selected_lad):
    try:
        if not selected_lad:
            return go.Figure().add_annotation(text="Please select a Local Authority", 
                                           showarrow=False, font=dict(size=16, color=colors['text']))
        
        lad_data = tfr_clean[tfr_clean['LAD23NM'] == selected_lad].copy()
        
        if lad_data.empty:
            return go.Figure().add_annotation(text=f"No TFR data available for {selected_lad}", 
                                           showarrow=False, font=dict(size=14, color=colors['text']))
        
        # Convert for plotting
        lad_data['year_int'] = lad_data['year'].astype(int)
        lad_data = lad_data.sort_values('year_int')
        
        fig = go.Figure()
        
        # Enhanced LAD trend line
        fig.add_trace(
            go.Scatter(
                x=lad_data['year_int'],
                y=lad_data['tfr'],
                mode='lines+markers',
                name=selected_lad,
                line=dict(color=colors['primary'], width=4),
                marker=dict(size=8, color=colors['secondary'], 
                          line=dict(color='white', width=2))
            )
        )
        
        # Enhanced UK average
        uk_avg_by_year = tfr_clean.groupby('year')['tfr'].mean().reset_index()
        uk_avg_by_year['year_int'] = uk_avg_by_year['year'].astype(int)
        uk_avg_by_year = uk_avg_by_year.sort_values('year_int')
        
        fig.add_trace(
            go.Scatter(
                x=uk_avg_by_year['year_int'],
                y=uk_avg_by_year['tfr'],
                mode='lines',
                name='UK Average',
                line=dict(color='gray', width=3, dash='dash'),
                opacity=0.8
            )
        )
        
        # Enhanced replacement level line
        fig.add_hline(y=2.1, line_dash="dot", line_color=colors['warning'], line_width=3,
                     annotation_text="UK Replacement Level (2.1)", 
                     annotation_font=dict(color=colors['warning'], size=12))
        
        fig.update_layout(
            title=dict(
                text=f"TFR Trend Analysis: {selected_lad}",
                x=0.5,
                font=dict(size=16, color=colors['primary'], family="Arial Black")
            ),
            xaxis_title="Year",
            yaxis_title="Total Fertility Rate",
            height=400,
            hovermode='x unified',
            plot_bgcolor='rgba(248,249,250,0.8)',
            paper_bgcolor='white'
        )
        
        return fig
        
    except Exception as e:
        print(f"Enhanced TFR trend error: {e}")
        return go.Figure().add_annotation(text=f"Trend Error: {str(e)[:50]}...", 
                                       showarrow=False, font=dict(size=14, color='red'))

# Enhanced ASFR trend with professional styling
@app.callback(
    Output('asfr-trend', 'figure'),
    [Input('lad-dropdown', 'value'),
     Input('age-dropdown', 'value')]
)
def update_asfr_trend(selected_lad, selected_age):
    try:
        if not selected_lad or not selected_age:
            return go.Figure().add_annotation(text="Please select LAD and age", 
                                           showarrow=False, font=dict(size=16, color=colors['text']))
        
        lad_age_data = asfr_clean[
            (asfr_clean['LAD23NM'] == selected_lad) &
            (asfr_clean['age'] == selected_age)
        ].copy()
        
        if lad_age_data.empty:
            return go.Figure().add_annotation(
                text=f"No ASFR data for {selected_lad}, Age {selected_age}", 
                showarrow=False, font=dict(size=14, color=colors['text'])
            )
        
        # Convert for plotting
        lad_age_data['year_int'] = lad_age_data['year'].astype(int)
        lad_age_data = lad_age_data.sort_values('year_int')
        
        fig = go.Figure()
        
        # Enhanced LAD ASFR trend
        fig.add_trace(
            go.Scatter(
                x=lad_age_data['year_int'],
                y=lad_age_data['fertility_rate'],
                mode='lines+markers',
                name=f"{selected_lad} (Age {selected_age})",
                line=dict(color=colors['secondary'], width=4),
                marker=dict(size=8, color=colors['accent'], 
                          line=dict(color='white', width=2))
            )
        )
        
        # Enhanced UK average for age
        uk_avg_age = asfr_clean[asfr_clean['age'] == selected_age].groupby('year')['fertility_rate'].mean().reset_index()
        uk_avg_age['year_int'] = uk_avg_age['year'].astype(int)
        uk_avg_age = uk_avg_age.sort_values('year_int')
        
        fig.add_trace(
            go.Scatter(
                x=uk_avg_age['year_int'],
                y=uk_avg_age['fertility_rate'],
                mode='lines',
                name='UK Average',
                line=dict(color='gray', width=3, dash='dash'),
                opacity=0.8
            )
        )
        
        fig.update_layout(
            title=dict(
                text=f"ASFR Trend Analysis (Age {selected_age}): {selected_lad}",
                x=0.5,
                font=dict(size=16, color=colors['primary'], family="Arial Black")
            ),
            xaxis_title="Year",
            yaxis_title="Age-Specific Fertility Rate",
            height=400,
            hovermode='x unified',
            plot_bgcolor='rgba(248,249,250,0.8)',
            paper_bgcolor='white'
        )
        
        return fig
        
    except Exception as e:
        print(f"Enhanced ASFR trend error: {e}")
        return go.Figure().add_annotation(text=f"Trend Error: {str(e)[:50]}...", 
                                       showarrow=False, font=dict(size=14, color='red'))

# run
if __name__ == '__main__':
    print("Starting Enhanced UK Fertility Dashboard...")
    print("Professional styling with GLA-inspired design elements")
    print("Fertility colour schemes preserved (RdYlBu_r for TFR, Plasma for ASFR)")
    print("Enhanced loading spinner and professional UI")
    print("Access at: http://127.0.0.1:8067")
    print("Use Ctrl+C to stop the server")
    app.run(debug=True, port=8067)

Enhanced dashboard ready: 31 years, 35 ages, 318 LADs
Starting Enhanced UK Fertility Dashboard...
Professional styling with GLA-inspired design elements
Fertility colour schemes preserved (RdYlBu_r for TFR, Plasma for ASFR)
Enhanced loading spinner and professional UI
Access at: http://127.0.0.1:8067
Use Ctrl+C to stop the server

In [9]:
# Read CSV files
core_largesites_df = pd.read_csv('/Users/user1/Documents/mapping_housing_trajectories/merged_Core_Largesites_gdf.csv')
ward_savills_df = pd.read_csv('/Users/user1/Documents/mapping_housing_trajectories/merged_ward_savills_gdf.csv')

In [15]:
# Read CSV and convert geometry
# shapely.wkt does not provide safe_wkt_loads; use wkt.loads and handle null/invalid values
def _safe_load_wkt(val):
	if pd.isna(val):
		return None
	try:
		return wkt.loads(val)
	except Exception:
		return None

core_largesites_df['geometry'] = core_largesites_df['geometry'].apply(_safe_load_wkt)
ward_savills_df['geometry'] = ward_savills_df['geometry'].apply(_safe_load_wkt)
merged_Core_Largesites_gdf = gpd.GeoDataFrame(core_largesites_df, geometry='geometry', crs="EPSG:4326")
merged_ward_savills_gdf = gpd.GeoDataFrame(ward_savills_df, geometry='geometry', crs="EPSG:4326")

NameError: name 'core_largesites_df' is not defined

In [11]:
merged_Core_Largesites_gdf

,wd22cd,2021,2022,2023,2024,2025,2026,2027,2028,2029,...,2044,2045,2046,2047,2048,2049,2050,wd22nm,lad22nm,geometry
0,E05009317,NaN,NaN,NaN,NaN,NaN,93,30,0,0,...,0,0,0,0,0,0,0,Bethnal Green,Tower Hamlets,"POLYGON ((-0.03704 51.52425, -0.05001 51.52107..."
1,E05009318,NaN,NaN,NaN,NaN,NaN,727,1380,1711,933,...,300,379,200,64,0,0,0,Blackwall & Cubitt Town,Tower Hamlets,"POLYGON ((0.00599 51.51016, 0.00984 51.50843, ..."
2,E05009319,NaN,NaN,NaN,NaN,NaN,75,-63,0,145,...,0,0,0,0,0,0,0,Bow East,Tower Hamlets,"POLYGON ((-0.01655 51.54333, -0.02127 51.53701..."
3,E05009320,NaN,NaN,NaN,NaN,NaN,0,0,0,0,...,0,0,0,0,0,0,0,Bow West,Tower Hamlets,"POLYGON ((-0.02101 51.52793, -0.03017 51.5261,..."
4,E05009321,NaN,NaN,NaN,NaN,NaN,657,676,254,142,...,0,0,0,0,0,0,0,Bromley North,Tower Hamlets,"POLYGON ((-0.00781 51.52533, -0.02394 51.52318..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
674,E05014115,NaN,NaN,NaN,NaN,NaN,5,0,0,0,...,0,0,0,0,0,0,0,Streatham St Leonard's,Lambeth,"POLYGON ((-0.12691 51.43817, -0.12694 51.4381,..."
675,E05014116,NaN,NaN,NaN,NaN,NaN,0,0,0,0,...,0,0,0,0,0,0,0,Streatham Wells,Lambeth,"POLYGON ((-0.11781 51.43306, -0.11426 51.42426..."
676,E05014117,NaN,NaN,NaN,NaN,NaN,253,200,400,280,...,0,0,0,0,0,0,0,Vauxhall,Lambeth,"POLYGON ((-0.11819 51.4924, -0.11462 51.48694,..."
677,E05014118,NaN,NaN,NaN,NaN,NaN,101,-258,0,0,...,0,0,0,0,0,0,0,Waterloo & South Bank,Lambeth,"POLYGON ((-0.10647 51.50157, -0.11147 51.49646..."
678,E05014119,NaN,NaN,NaN,NaN,NaN,0,0,0,0,...,0,0,0,0,0,0,0,West Dulwich,Lambeth,"POLYGON ((-0.0929 51.44108, -0.08935 51.43202,..."

In [14]:
merged_ward_savills_gdf

NameError: name 'merged_ward_savills_gdf' is not defined

In [42]:
# --------- Dual Animated Map Function ---------
def create_dual_animated_map():
    ward_numeric = merged_ward_savills_gdf.select_dtypes(include=[np.number]).columns.tolist()
    sites_numeric = merged_Core_Largesites_gdf.select_dtypes(include=[np.number]).columns.tolist()
    
    ward_years = [col for col in ward_numeric if str(col).isdigit() and len(str(col)) == 4]
    sites_years = [col for col in sites_numeric if str(col).isdigit() and len(str(col)) == 4]
    common_years = sorted(set(ward_years) & set(sites_years))
    
    if not common_years:
        return None, []
    
    # Convert to integers for proper sorting
    common_years = sorted([int(year) for year in common_years])
    
    ward_gdf_web = merged_ward_savills_gdf.to_crs('EPSG:4326') if merged_ward_savills_gdf.crs != 'EPSG:4326' else merged_ward_savills_gdf
    sites_gdf_web = merged_Core_Largesites_gdf.to_crs('EPSG:4326') if merged_Core_Largesites_gdf.crs != 'EPSG:4326' else merged_Core_Largesites_gdf
    
    fig = make_subplots(
        rows=1, cols=2,
        subplot_titles=('Savills Trajectory', 'Core Largesites Baseline'),
        specs=[[{'type': 'mapbox'}, {'type': 'mapbox'}]],
        horizontal_spacing=0.08
    )
    
    frames = []
    for year in common_years:
        frame_data = []
        ward_clean = ward_gdf_web.dropna(subset=[str(year), 'geometry'])
        sites_clean = sites_gdf_web.dropna(subset=[str(year), 'geometry'])
        
        # Calculate separate ranges for each dataset
        ward_values = ward_clean[str(year)].dropna().values if not ward_clean.empty else [0]
        sites_values = sites_clean[str(year)].dropna().values if not sites_clean.empty else [0]
        
        ward_min, ward_max = 0, max(ward_values) if len(ward_values) > 0 else 100
        sites_min, sites_max = 0, max(sites_values) if len(sites_values) > 0 else 100
        
        # Savills data with blue to orange colorscale and separate legend
        frame_data.append(
            go.Choroplethmapbox(
                geojson=ward_clean.__geo_interface__,
                locations=ward_clean.index,
                z=ward_clean[str(year)],
                colorscale=[[0, '#000080'], [1, '#FF4500']],  # Dark blue to dark orange
                zmin=ward_min,
                zmax=ward_max,
                text=ward_clean['wd22nm'],
                hovertemplate=f'<b>%{{text}}</b><br>Savills {year}: %{{z}}<extra></extra>',
                marker_opacity=0.7,
                marker_line_width=0.5,
                marker_line_color='white',
                name='Savills Data',
                showscale=True,
                colorbar=dict(
                    title=f"Savills Units ({year})", 
                    x=0.45, 
                    len=0.8, 
                    thickness=15,
                    title_side="right",
                )
            )
        )
        
        # Core Sites data with blue to orange colorscale and separate legend
        frame_data.append(
            go.Choroplethmapbox(
                geojson=sites_clean.__geo_interface__,
                locations=sites_clean.index,
                z=sites_clean[str(year)],
                colorscale=[[0, '#000080'], [1, '#FF4500']],  # Dark blue to dark orange
                zmin=sites_min,
                zmax=sites_max,
                text=sites_clean['wd22nm'],
                hovertemplate=f'<b>%{{text}}</b><br>Core Sites {year}: %{{z}}<extra></extra>',
                marker_opacity=0.7,
                marker_line_width=0.5,
                marker_line_color='white',
                name='Core Sites Data',
                showscale=True,
                colorbar=dict(
                    title=f"Core Sites Units ({year})", 
                    x=1.02, 
                    len=0.8, 
                    thickness=15,
                    title_side="right",
                )
            )
        )
        
        frames.append(go.Frame(data=frame_data, name=str(year)))
    
    # Initial traces
    if frames:
        fig.add_trace(frames[0].data[0], row=1, col=1)
        fig.add_trace(frames[0].data[1], row=1, col=2)
    
    fig.update_layout(
        title='Housing Units Added',
        mapbox1=dict(style='carto-positron', center={'lat': 51.5074, 'lon': -0.1278}, zoom=8),
        mapbox2=dict(style='carto-positron', center={'lat': 51.5074, 'lon': -0.1278}, zoom=8),
        height=600,
        width=1200,
        showlegend=False,
        updatemenus=[{
            'type': 'buttons',
            'showactive': False,
            'x': 0.1,
            'y': 1.02,
            'xanchor': 'right',
            'yanchor': 'top',
            'buttons': [
                {
                    'label': 'Play',
                    'method': 'animate',
                    'args': [None, {
                        'frame': {'duration': 1500, 'redraw': True},
                        'fromcurrent': True,
                        'transition': {'duration': 750}
                    }]
                },
                {
                    'label': 'Pause', 
                    'method': 'animate',
                    'args': [[None], {
                        'frame': {'duration': 0, 'redraw': False},
                        'mode': 'immediate',
                        'transition': {'duration': 0}
                    }]
                }
            ]
        }],
        sliders=[{
            'active': 0,
            'yanchor': 'top',
            'xanchor': 'left',
            'currentvalue': {
                'font': {'size': 16},
                'prefix': 'Year: ',
                'visible': True,
                'xanchor': 'right'
            },
            'transition': {'duration': 750, 'easing': 'cubic-in-out'},
            'pad': {'b': 10, 't': 50},
            'len': 0.9,
            'x': 0.1,
            'y': 0,
            'steps': [
                {
                    'args': [[year], {
                        'frame': {'duration': 750, 'redraw': True},
                        'mode': 'immediate',
                        'transition': {'duration': 750}
                    }],
                    'label': str(year),
                    'method': 'animate'
                } for year in common_years
            ]
        }]
    )
    
    fig.frames = frames
    return fig, common_years

# --------- Interactive Line Graph Function ---------
def create_interactive_line_graphs():
    merged_ward_savills_gdf_line = merged_ward_savills_gdf.drop(columns=['2021'], errors='ignore')
    merged_Core_Largesites_gdf_line = merged_Core_Largesites_gdf.drop(columns=['2021'], errors='ignore')
    
    ward_numeric = merged_ward_savills_gdf_line.select_dtypes(include=[np.number]).columns.tolist()
    sites_numeric = merged_Core_Largesites_gdf_line.select_dtypes(include=[np.number]).columns.tolist()
    
    ward_years = [col for col in ward_numeric if str(col).isdigit() and len(str(col)) == 4]
    sites_years = [col for col in sites_numeric if str(col).isdigit() and len(str(col)) == 4]
    common_years = sorted(set(ward_years) & set(sites_years))
    
    if not common_years:
        return None
    
    # Convert to integers for proper sorting
    common_years = sorted([int(year) for year in common_years])
    
    ward_names = merged_ward_savills_gdf['wd22nm'].dropna().unique()
    ward_names = sorted([name for name in ward_names if pd.notna(name)])
    if len(ward_names) == 0:
        return None
    
    fig = make_subplots(rows=1, cols=2, subplot_titles=('Savills Trajectory', 'Core Largesites Baseline'), x_title='Year', y_title='Housing Units')
    
    all_traces = []
    for i, ward_name in enumerate(ward_names):
        ward_savills_data = merged_ward_savills_gdf[merged_ward_savills_gdf['wd22nm'] == ward_name]
        ward_sites_data = merged_Core_Largesites_gdf[merged_Core_Largesites_gdf['wd22nm'] == ward_name]
        
        savills_values = [ward_savills_data[str(year)].iloc[0] if str(year) in ward_savills_data.columns else 0 for year in common_years] if not ward_savills_data.empty else [0]*len(common_years)
        sites_values = [ward_sites_data[str(year)].iloc[0] if str(year) in ward_sites_data.columns else 0 for year in common_years] if not ward_sites_data.empty else [0]*len(common_years)
        
        trace_savills = go.Scatter(x=common_years, y=savills_values, mode='lines+markers', name=f'{ward_name} (Savills)', visible=(i==0), line=dict(color='#0074D9', width=2), marker=dict(size=6))
        trace_sites = go.Scatter(x=common_years, y=sites_values, mode='lines+markers', name=f'{ward_name} (Sites)', visible=(i==0), line=dict(color='#FF851B', width=2), marker=dict(size=6))
        
        fig.add_trace(trace_savills, row=1, col=1)
        fig.add_trace(trace_sites, row=1, col=2)
        all_traces.extend([trace_savills, trace_sites])
    
    dropdown_buttons = []
    for i, ward_name in enumerate(ward_names):
        visibility = [False]*len(all_traces)
        visibility[i*2] = True
        visibility[i*2+1] = True
        dropdown_buttons.append(dict(label=ward_name, method="update", args=[{"visible": visibility}]))
    
    fig.update_layout(
        title='Housing Trajectories by Ward',
        height=600,
        width=1200,
        showlegend=True,
        updatemenus=[dict(buttons=dropdown_buttons, direction="down", showactive=True, x=0.5, xanchor="center", y=1.15, yanchor="top")]
    )
    
    fig.update_xaxes(title_text="Year", row=1, col=1)
    fig.update_xaxes(title_text="Year", row=1, col=2)
    fig.update_yaxes(title_text="Housing Units", row=1, col=1)
    fig.update_yaxes(title_text="Housing Units", row=1, col=2)
    
    return fig

# ---------------- Initialize Figures ----------------
fig_dual_animated, common_years = create_dual_animated_map()
fig_line_graphs = create_interactive_line_graphs()

# ---------------- Dash App Layout ----------------
app = dash.Dash(__name__, external_stylesheets=[dbc.themes.SANDSTONE])

# Add GLA favicon and custom loading spinner
app.index_string = '''
<!DOCTYPE html>
<html>
    <head>
        {%metas%}
        <title>{%title%}</title>
        <link rel="icon" href="https://resource.esriuk.com/wp-content/uploads/2017/06/GLA-Logo-Resized.png" type="image/png">
        {%favicon%}
        {%css%}
        <style>
            /* Loading spinner overlay */
            .loading-overlay {
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                background: linear-gradient(135deg, #0074D9 0%, #FF851B 100%);
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
                z-index: 9999;
                transition: opacity 0.5s ease-out;
            }
            
            /* Spinner animation */
            .spinner {
                width: 80px;
                height: 80px;
                border: 6px solid rgba(255, 255, 255, 0.3);
                border-top: 6px solid white;
                border-radius: 50%;
                animation: spin 1s linear infinite;
                margin-bottom: 20px;
            }
            
            @keyframes spin {
                0% { transform: rotate(0deg); }
                100% { transform: rotate(360deg); }
            }
            
            /* Loading text */
            .loading-text {
                color: white;
                font-family: Arial, sans-serif;
                font-size: 24px;
                font-weight: bold;
                text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
                margin-bottom: 10px;
            }
            
            .loading-subtext {
                color: rgba(255, 255, 255, 0.9);
                font-family: Arial, sans-serif;
                font-size: 16px;
                text-align: center;
                max-width: 300px;
            }
            
            /* GLA logo in loading screen */
            .loading-logo {
                width: 60px;
                height: 60px;
                margin-bottom: 30px;
                border-radius: 50%;
                background: white;
                display: flex;
                align-items: center;
                justify-content: center;
                box-shadow: 0 4px 15px rgba(0,0,0,0.2);
            }
            
            .loading-logo img {
                width: 40px;
                height: 40px;
                object-fit: contain;
            }
        </style>
    </head>
    <body>
        <!-- Loading overlay -->
        <div id="loading-overlay" class="loading-overlay">
            <div class="loading-logo">
                <img src="https://resource.esriuk.com/wp-content/uploads/2017/06/GLA-Logo-Resized.png" alt="GLA Logo">
            </div>
            <div class="spinner"></div>
            <div class="loading-text">Loading Dashboard</div>
            <div class="loading-subtext">Preparing housing trajectory visualisations...</div>
        </div>
        
        {%app_entry%}
        <footer>
            {%config%}
            {%scripts%}
            {%renderer%}
        </footer>
        
        <script>
            // Hide loading overlay when page is fully loaded
            window.addEventListener('load', function() {
                setTimeout(function() {
                    const overlay = document.getElementById('loading-overlay');
                    if (overlay) {
                        overlay.style.opacity = '0';
                        setTimeout(function() {
                            overlay.style.display = 'none';
                        }, 500);
                    }
                }, 1000); // Show spinner for at least 1 second
            });
            
            // Also hide when Dash is ready
            document.addEventListener('DOMContentLoaded', function() {
                // Wait for Dash to render main content
                const checkDashReady = setInterval(function() {
                    const dashContainer = document.querySelector('[data-dash-is-loading="false"]');
                    if (dashContainer) {
                        clearInterval(checkDashReady);
                        setTimeout(function() {
                            const overlay = document.getElementById('loading-overlay');
                            if (overlay && overlay.style.display !== 'none') {
                                overlay.style.opacity = '0';
                                setTimeout(function() {
                                    overlay.style.display = 'none';
                                }, 500);
                            }
                        }, 500);
                    }
                }, 100);
            });
        </script>
    </body>
</html>
'''
 
primary_color = "#0074D9"  # Blue
secondary_color = "#FF851B"  # Orange
bg_color = "#F5F7FA"

# Ensure we have valid numeric years for the slider
if not common_years:
    common_years = [2022, 2023, 2024, 2025]  # Default years

min_year = min(common_years) if common_years else 2022
max_year = max(common_years) if common_years else 2050
default_year = min_year

app.layout = dbc.Container([
    
    html.Div([
        html.H1("Housing Units Dashboard", style={'textAlign': 'center', 'color': primary_color, 'fontWeight': 'bold', 'marginTop': 20, 'textShadow': '2px 2px 4px #888'}),
        html.Hr(style={'borderColor': secondary_color, 'height': '3px'})
    ]),
    
    # Metric Cards WITHOUT dcc.Loading wrappers - custom loading overlay handles this
    dbc.Row([
        dbc.Col(
            dbc.Card([
                dbc.CardBody([
                    html.H4("Number of Houses Added", className="card-title", style={'color': primary_color}),
                    html.H5(id="year-display-savills", style={'color': '#666', 'fontSize': '14px'}),
                    html.H2(id="savills-total", className="card-text")
                ])
            ], style={'borderLeft': f'5px solid {secondary_color}', 'boxShadow': '3px 3px 15px rgba(0,0,0,0.1)'})
        ),
        
        dbc.Col(
            dbc.Card([
                dbc.CardBody([
                    html.H4("Number of Houses Added", className="card-title", style={'color': secondary_color}),
                    html.H5(id="year-display-sites", style={'color': '#666', 'fontSize': '14px'}),
                    html.H2(id="sites-total", className="card-text")
                ])
            ], style={'borderLeft': f'5px solid {primary_color}', 'boxShadow': '3px 3px 15px rgba(0,0,0,0.1)'})
        ),
    ], className="mb-4"),
    
    # Year Slider for controlling everything - moved above maps
    html.Div([
        html.H4("Select Year", style={'color': primary_color, 'marginBottom': 10}),
        dcc.Slider(
            id='year-slider',
            min=min_year,
            max=max_year,
            value=2027,
            marks={year: str(year) for year in common_years[::2]} if common_years else {},
            step=1,
            tooltip={"placement": "bottom", "always_visible": True},
            included=False
        )
    ], style={'marginBottom': 30, 'padding': '20px', 'backgroundColor': 'white', 'borderRadius': '10px', 'boxShadow': '3px 3px 15px rgba(0,0,0,0.1)'}),
    
    # Animated Comparison Map WITHOUT dcc.Loading wrapper
    html.H3("Animated Comparison Map", style={'color': primary_color, 'fontWeight': 'bold', 'textAlign': 'center', 'marginTop': 20}),
    dcc.Graph(
        id='animated-map', 
        figure=fig_dual_animated if fig_dual_animated else go.Figure(), 
        style={'height': '650px', 'border': f'3px solid {secondary_color}', 'borderRadius': '10px', 'boxShadow': '5px 5px 15px rgba(0,0,0,0.2)'}
    ),
    
    # Interactive Line Graphs by Ward WITHOUT dcc.Loading wrapper
    html.H3("Interactive Line Graphs by Ward", style={'color': primary_color, 'fontWeight': 'bold', 'textAlign': 'center', 'marginTop': 30}),
    dcc.Graph(
        figure=fig_line_graphs if fig_line_graphs else go.Figure(), 
        style={'height': '650px', 'border': f'3px solid {secondary_color}', 'borderRadius': '10px', 'boxShadow': '5px 5px 15px rgba(0,0,0,0.2)'}
    ),
    
    html.Div([
        html.P("This is an automated report produced by the Greater London Authority (GLA)", 
               style={'margin': '10px 0', 'fontSize': '14px', 'color': '#666'}),
        html.P([
            "If you require further information, please email ",
            html.A("Sebastian.Heslin-Rees@london.gov.uk", 
                   href="mailto:Sebastian.Heslin-Rees@london.gov.uk",
                   style={'color': primary_color, 'textDecoration': 'underline'})
        ], style={'margin': '10px 0', 'fontSize': '14px', 'color': '#666'})
    ], className="footer", style={'textAlign': 'center', 'marginTop': 50, 'padding': '20px', 'backgroundColor': '#f8f9fa', 'borderTop': f'2px solid {secondary_color}', 'borderRadius': '5px'})
    
], fluid=True, style={'backgroundColor': bg_color, 'padding': '20px'})

# Callback to update metric cards and year display based on selected year
@app.callback(
    [Output('savills-total', 'children'),
     Output('sites-total', 'children'),
     Output('year-display-savills', 'children'),
     Output('year-display-sites', 'children')],
    [Input('year-slider', 'value')]
)
def update_metrics(selected_year):
    year_str = str(selected_year)
    
    # Calculate totals for selected year
    savills_total = 0
    sites_total = 0
    
    if year_str in merged_ward_savills_gdf.columns:
        savills_total = merged_ward_savills_gdf[year_str].sum()
    
    if year_str in merged_Core_Largesites_gdf.columns:
        sites_total = merged_Core_Largesites_gdf[year_str].sum()
    
    year_display = f"Year {selected_year}"
    
    return f"{int(savills_total):,}", f"{int(sites_total):,}", year_display, year_display

if __name__ == "__main__":
    app.run(port= 1800, debug=True)

NameError: name 'merged_ward_savills_gdf' is not defined

In [ ]:
import dash
import dash_bootstrap_components as dbc
from dash import dcc, html, Input, Output
import plotly.express as px
import plotly.graph_objects as go

# --- Data Preparation ---
print("Preparing fertility rate data for dashboard...")

# Prepare TFR data
tfr_clean = tfr_merged[['LAD23CD', 'LAD23NM', 'geometry', 'year', 'tfr']].copy()
if tfr_clean.crs is None:
    tfr_clean = tfr_clean.set_crs("EPSG:27700", allow_override=True)
tfr_clean = tfr_clean.to_crs(epsg=4326)
tfr_clean['geometry'] = tfr_clean['geometry'].simplify(tolerance=0.008, preserve_topology=True)
tfr_clean = tfr_clean[tfr_clean.is_valid].reset_index(drop=True)

# Prepare ASFR data  
asfr_clean = asfr_merged[['LAD23CD','LAD23NM','geometry','age','year','fertility_rate']].copy()
if asfr_clean.crs is None:
    asfr_clean = asfr_clean.set_crs("EPSG:27700", allow_override=True)
asfr_clean = asfr_clean.to_crs(epsg=4326)
asfr_clean['geometry'] = asfr_clean['geometry'].simplify(tolerance=0.008, preserve_topology=True)
asfr_clean = asfr_clean[asfr_clean.is_valid].reset_index(drop=True)

# Get available options
years = sorted(tfr_clean['year'].unique())
ages = sorted(asfr_clean['age'].unique())
lads = sorted(tfr_clean['LAD23NM'].unique())

print(f"✅ Data prepared: {len(years)} years, {len(ages)} ages, {len(lads)} local authorities")

# --- Initialise Dash App ---
app = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])
app.title = "UK Fertility Rate Dashboard"

# --- App Layout ---
app.layout = dbc.Container([
    # Header
    dbc.Row([
        dbc.Col([
            html.H1("🇬🇧 UK Fertility Rate Dashboard", 
                   className="text-center mb-4",
                   style={'color': '#2E8B57', 'fontWeight': 'bold'}),
            html.Hr(style={'borderColor': '#FF6B6B', 'borderWidth': '3px'})
        ])
    ]),
    
    # Control Panel
    dbc.Card([
        dbc.CardBody([
            html.H4("📊 Dashboard Controls", className="mb-3", style={'color': '#2E8B57'}),
            
            dbc.Row([
                # Year Selection
                dbc.Col([
                    html.Label("📅 Select Year:", className="fw-bold"),
                    dcc.Dropdown(
                        id='year-dropdown',
                        options=[{'label': f"{year}", 'value': year} for year in years],
                        value=years[-1],  # Start with most recent year
                        clearable=False,
                        style={'marginBottom': '10px'}
                    )
                ], width=3),
                
                # Age Selection (for ASFR)
                dbc.Col([
                    html.Label("👶 Select Age (ASFR):", className="fw-bold"),
                    dcc.Dropdown(
                        id='age-dropdown',
                        options=[{'label': f"Age {age}", 'value': age} for age in ages],
                        value=30,  # Default to age 30
                        clearable=False,
                        style={'marginBottom': '10px'}
                    )
                ], width=3),
                
                # LAD Selection (for line graphs)
                dbc.Col([
                    html.Label("🏘️ Select Local Authority:", className="fw-bold"),
                    dcc.Dropdown(
                        id='lad-dropdown',
                        options=[{'label': lad, 'value': lad} for lad in lads[:50]], # Show first 50 for performance
                        value="Manchester",  # Default LAD
                        clearable=False,
                        style={'marginBottom': '10px'}
                    )
                ], width=6)
            ])
        ])
    ], className="mb-4", style={'backgroundColor': '#F8F9FA'}),
    
    # Maps Row
    dbc.Row([
        # TFR Map
        dbc.Col([
            dbc.Card([
                dbc.CardHeader(html.H5("🗺️ Total Fertility Rate (TFR) Map", className="text-center mb-0")),
                dbc.CardBody([
                    dcc.Graph(id='tfr-map', style={'height': '500px'})
                ])
            ])
        ], width=6),
        
        # ASFR Map
        dbc.Col([
            dbc.Card([
                dbc.CardHeader(html.H5("🗺️ Age-Specific Fertility Rate (ASFR) Map", className="text-center mb-0")),
                dbc.CardBody([
                    dcc.Graph(id='asfr-map', style={'height': '500px'})
                ])
            ])
        ], width=6)
    ], className="mb-4"),
    
    # Line Graphs Row
    dbc.Row([
        # TFR Trend
        dbc.Col([
            dbc.Card([
                dbc.CardHeader(html.H5("📈 TFR Trend Over Time", className="text-center mb-0")),
                dbc.CardBody([
                    dcc.Graph(id='tfr-line', style={'height': '400px'})
                ])
            ])
        ], width=6),
        
        # ASFR Trend
        dbc.Col([
            dbc.Card([
                dbc.CardHeader(html.H5("📈 ASFR Trend Over Time", className="text-center mb-0")),
                dbc.CardBody([
                    dcc.Graph(id='asfr-line', style={'height': '400px'})
                ])
            ])
        ], width=6)
    ], className="mb-4"),
    
    # Footer
    dbc.Row([
        dbc.Col([
            html.Hr(),
            html.P("💡 This dashboard visualises UK fertility rates using ONS data. TFR shows total fertility rate, ASFR shows age-specific fertility rate.",
                   className="text-muted text-center"),
            html.P("🔄 Use the controls above to explore different years, ages, and local authorities.",
                   className="text-muted text-center")
        ])
    ])
    
], fluid=True, style={'padding': '20px'})

# --- Metric Cards Callback ---
@app.callback(
    [Output('tfr-title', 'children'),
     Output('comparison-title', 'children'),
     Output('current-tfr', 'children'),
     Output('tfr-comparison', 'children'),
     Output('replacement-status', 'children')],
    [Input('year-dropdown', 'value'),
     Input('lad-dropdown', 'value')]
)
def update_metrics(selected_year, selected_lad):
    if not selected_year or not selected_lad:
        return (
            "Total Fertility Rate",
            "vs UK Average", 
            "--", 
            "--", 
            "--"
        )
    
    # Get LAD TFR for selected year and area
    lad_tfr = tfr_clean[
        (tfr_clean['year'] == selected_year) & 
        (tfr_clean['LAD23NM'] == selected_lad)
    ]
    
    # Get UK average for selected year
    uk_avg = tfr_clean[tfr_clean['year'] == selected_year]['tfr'].mean()
    
    if lad_tfr.empty:
        current_tfr_val = "--"
        comparison_val = "--"
        replacement_val = "--"
    else:
        current_tfr_val = f"{lad_tfr.iloc[0]['tfr']:.2f}"
        
        # Calculate difference from UK average
        diff = lad_tfr.iloc[0]['tfr'] - uk_avg
        if diff > 0:
            comparison_val = f"+{diff:.2f}"
        else:
            comparison_val = f"{diff:.2f}"
        
        # Replacement level status
        tfr_val = lad_tfr.iloc[0]['tfr']
        if tfr_val >= 2.1:
            replacement_val = "Above replacement"
        else:
            replacement_val = f"{2.1 - tfr_val:.2f} below"
    
    # Dynamic titles
    tfr_title = f"Total Fertility Rate for {selected_lad} in {selected_year}"
    comparison_title = f"{selected_lad} vs UK Average"
    
    return tfr_title, comparison_title, current_tfr_val, comparison_val, replacement_val

# --- TFR Map Callback ---
@app.callback(
    Output('tfr-map', 'figure'),
    Input('year-dropdown', 'value')
)
def update_tfr_map(selected_year):
    # Filter data
    filtered_tfr = tfr_clean[tfr_clean['year'] == selected_year]
    
    if filtered_tfr.empty:
        return go.Figure().add_annotation(text="No data available", showarrow=False)
    
    # Create choropleth map
    fig = px.choropleth_mapbox(
        filtered_tfr,
        geojson=filtered_tfr.__geo_interface__,
        locations='LAD23CD',
        featureidkey='properties.LAD23CD',
        color='tfr',
        hover_name='LAD23NM',
        hover_data={'tfr': ':.3f', 'year': True, 'LAD23CD': False},
        color_continuous_scale='RdYlBu_r',  # Red=high, Blue=low fertility
        mapbox_style='carto-positron',
        zoom=5.2,
        center={"lat": 54.5, "lon": -2.5},
        opacity=0.8,
        title=f"TFR in {selected_year}"
    )
    
    fig.update_layout(
        margin={"r":0,"t":40,"l":0,"b":0},
        title_font_size=14,
        coloraxis_colorbar=dict(
            title="TFR",
            title_font_size=12
        )
    )
    return fig

# --- ASFR Map Callback ---
@app.callback(
    Output('asfr-map', 'figure'),
    Input('year-dropdown', 'value'),
    Input('age-dropdown', 'value')
)
def update_asfr_map(selected_year, selected_age):
    # Filter data
    filtered_asfr = asfr_clean[
        (asfr_clean['year'] == selected_year) &
        (asfr_clean['age'] == selected_age)
    ]
    
    if filtered_asfr.empty:
        return go.Figure().add_annotation(text="No data available", showarrow=False)
    
    # Create choropleth map
    fig = px.choropleth_mapbox(
        filtered_asfr,
        geojson=filtered_asfr.__geo_interface__,
        locations='LAD23CD',
        featureidkey='properties.LAD23CD',
        color='fertility_rate',
        hover_name='LAD23NM',
        hover_data={'fertility_rate': ':.4f', 'year': True, 'age': True, 'LAD23CD': False},
        color_continuous_scale='Plasma',
        mapbox_style='carto-positron',
        zoom=5.2,
        center={"lat": 54.5, "lon": -2.5},
        opacity=0.8,
        title=f"ASFR Age {selected_age} in {selected_year}"
    )
    
    fig.update_layout(
        margin={"r":0,"t":40,"l":0,"b":0},
        title_font_size=14,
        coloraxis_colorbar=dict(
            title="ASFR",
            title_font_size=12
        )
    )
    return fig

# --- TFR Line Graph Callback ---
@app.callback(
    Output('tfr-line', 'figure'),
    Input('lad-dropdown', 'value')
)
def update_tfr_line(selected_lad):
    if not selected_lad:
        return go.Figure().add_annotation(text="Please select a Local Authority", showarrow=False)
    
    # Filter data
    filtered_tfr = tfr_clean[tfr_clean['LAD23NM'] == selected_lad]
    
    if filtered_tfr.empty:
        return go.Figure().add_annotation(text=f"No TFR data for {selected_lad}", showarrow=False)
    
    # Create line graph
    fig = px.line(
        filtered_tfr,
        x='year',
        y='tfr',
        title=f"TFR Trend: {selected_lad}",
        markers=True,
        line_shape='spline'
    )
    
    # Add replacement level reference line
    fig.add_hline(
        y=2.1, 
        line_dash="dash", 
        line_color="red",
        annotation_text="UK Replacement Level (2.1)",
        annotation_position="bottom right"
    )
    
    fig.update_layout(
        xaxis_title="Year",
        yaxis_title="Total Fertility Rate",
        title_font_size=14,
        height=380
    )
    
    return fig

# --- ASFR Line Graph Callback ---
@app.callback(
    Output('asfr-line', 'figure'),
    Input('lad-dropdown', 'value'),
    Input('age-dropdown', 'value')
)
def update_asfr_line(selected_lad, selected_age):
    if not selected_lad:
        return go.Figure().add_annotation(text="Please select a Local Authority", showarrow=False)
    
    # Filter data
    filtered_asfr = asfr_clean[
        (asfr_clean['LAD23NM'] == selected_lad) &
        (asfr_clean['age'] == selected_age)
    ]
    
    if filtered_asfr.empty:
        return go.Figure().add_annotation(text=f"No ASFR data for {selected_lad}, Age {selected_age}", showarrow=False)
    
    # Create line graph
    fig = px.line(
        filtered_asfr,
        x='year',
        y='fertility_rate',
        title=f"ASFR Trend: {selected_lad} (Age {selected_age})",
        markers=True,
        line_shape='spline',
        color_discrete_sequence=['#FF6B6B']
    )
    
    fig.update_layout(
        xaxis_title="Year",
        yaxis_title="Age-Specific Fertility Rate",
        title_font_size=14,
        height=380
    )
    
    return fig

# --- Run App ---
if __name__ == '__main__':
    print("🚀 Starting Fertility Rate Dashboard...")
    print("📍 Access your dashboard at: http://127.0.0.1:8050")
    print("💡 Use Ctrl+C to stop the server")
    app.run(debug=True, port=8090)

Preparing fertility rate data for dashboard...
✅ Data prepared: 31 years, 35 ages, 318 local authorities
🚀 Starting Fertility Rate Dashboard...
📍 Access your dashboard at: http://127.0.0.1:8050
💡 Use Ctrl+C to stop the server
✅ Data prepared: 31 years, 35 ages, 318 local authorities
🚀 Starting Fertility Rate Dashboard...
📍 Access your dashboard at: http://127.0.0.1:8050
💡 Use Ctrl+C to stop the server